### ISSUE TITLE
Fatal error HRESULT: 0x80070002

### ISSUE THREAD

**Issue by gigi81** [shilonosov/NugetUnicorn#1]
Hi,
When I run NugetUnicorn against my project I have this error message:
06/09/2016 10:40:26 +00:00 Fatal: error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

Running the command on another solution doesn't generate the error so I guess this is specific for that solution. Anyway the error message is not really helpful to track down the issue. Also having a stack trace in the error log entry would be probably useful to narrow down the source of the problem.

**Comment by shilonosov** [comment]
fixed
